### ISSUE TITLE
Chrome will no longer support

### ISSUE THREAD

**Issue by RockTribe** [BHSPitMonkey/ninjam-js#8]
I've been using the app for a while, it's very practical. But chrome says it will no longer support it, will you update it? Chrome gave it time until December.

Thanks...

**Comment by brylie** [comment]
What is the exact message you are seeing in Chrome? What is Chrome saying it will no longer support?

**Comment by RockTribe** [comment]
![Adffddsız](https://user-images.githubusercontent.com/98563570/192046751-03cba2c9-72ad-42ac-b59e-c62cfcb42a39.jpg)
Translation:

"Ninjam JS" is no longer supported
Older versions of Chrome apps won't open after December 2022.
You can check if a new version is available."

**Comment by canandlamp** [comment]
It is nice to be able to listen to live jamming from a public internet terminal

**Comment by BHSPitMonkey** [comment]
Unfortunately, Chrome is removing support for Chrome Apps entirely and it is not possible to implement a NINJAM client using Web Platform APIs (because TCP sockets are needed).

While it is possible to package ninjam-js as an Electron app (as I've done in some previous versions), you are likely better off simply using a more full-featured NINJAM client such as [wahjam](https://github.com/wahjam/wahjam) or [JamTaba](https://github.com/elieserdejesus/JamTaba).

I'd love to see a future in which NINJAM community servers become upgraded to support client connections over Web Sockets or QUIC (in addition to plain TCP), which could enable direct support from web browsers. As far as I know, this has not yet happened.

**Comment by RockTribe** [comment]
> Unfortunately, Chrome is removing support for Chrome Apps entirely and it is not possible to implement a NINJAM client using Web Platform APIs (because TCP sockets are needed).
> 
> While it is possible to package ninjam-js as an Electron app (as I've done in some previous versions), you are likely better off simply using a more full-featured NINJAM client such as [wahjam](https://github.com/wahjam/wahjam) or [JamTaba](https://github.com/elieserdejesus/JamTaba).
> 
> I'd love to see a future in which NINJAM community servers become upgraded to support client connections over Web Sockets or QUIC (in addition to plain TCP), which could enable direct support from web browsers. As far as I know, this has not yet happened.

Sorry to hear that, using the extension was very practical. Since there is no asio support, I was only using it for chat or to transmit the radio broadcast (ie I already use other applications), I hope we have a chance to use it again in the future.

**Comment by canandlamp** [comment]
On an Ubuntu linux system, how can the old setup be utilized by either a backdated version of Chrome, or by another browser?

**Comment by canandlamp** [comment]
Can the format of the web app be re-arranged for use by generic web browser or java on usb drive?
